language: go

go:
  - 1.16.x

git:
  depth: 1


env:
  global:
    - NAME=docker-commander
    - GO111MODULE=on


matrix:
  include:
    - env: _GOOS=linux _GOARCH=amd64
      os: linux
    - env: _GOOS=linux _GOARCH=386
      os: linux
    - env: _GOOS=linux _GOARCH=arm
      os: linux
    - env: _GOOS=linux _GOARCH=arm64
      os: linux
    - env: _GOOS=darwin _GOARCH=386
      os: osx
    - env: _GOOS=darwin _GOARCH=amd64
      os: osx
    - env: _GOOS=windows _GOARCH=386
      os: windows
    - env: _GOOS=windows _GOARCH=amd64
      os: windows



install: true

script:
  - ./ci/install_upx.sh
  - ./ci/build.sh
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - golangci-lint run --timeout=30m


deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "./dist/*"
  skip_cleanup: true
  draft: true
  on:
    tags: true

if: tag IS present